### ISSUE TITLE
Problem with receiving traces in OTEL Collector

### ISSUE THREAD

**Issue by davide-russo-tfs** [krzko/run-with-telemetry#20]
Hello,

I'm trying to do a simple test by using the _run-with-telemetry_ GH Action with the _Github Receiver_ by OpenTelemetry. 
The following services are running on my personal laptop:

- OpenTelemetry Collector v. 0.119.0
- Github Runner

I created a simple GH Action Workflow to deploy a few resources into a Databricks workspace. This is the config file:
```
name: deploy_databricks

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions: read-all

concurrency: 1

env: 
  DATABRICKS_TOKEN: ###
  otel-exporter-otlp-endpoint: localhost:4317
  otel-service-name: test_otel_github

jobs:
  deploy_resources:
    runs-on: self-hosted 
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main  # Download Databricks CLI

      - name: "Deploy resources with monitoring"
        uses: krzko/run-with-telemetry@v0.5.0
        with:
          otel-exporter-otlp-endpoint: ${{ env.otel-exporter-otlp-endpoint }}
          otel-service-name: ${{ env.otel-service-name }}
          step-name: Deploy resources with monitoring
          run: databricks bundle deploy
```

This is instead the config file of the OpenTelemetry collector that I'm using:
```
receivers:
  github:
    scrapers:
      scraper:
    webhook:
      endpoint: localhost:4317
    tls:
      insecure: true

exporters:
  debug:
    verbosity: basic

service:
  pipelines:
    traces:
      receivers: [github]
      exporters: [debug]
```

The workflow executes successfully but I don't receive any trace in output:

![Image](https://github.com/user-attachments/assets/b9b91d2c-e95f-4e83-92d1-eb5e97076df1)

In addition, I see the following error in the logs of the GH Workflow:

![Image](https://github.com/user-attachments/assets/306a00c7-249e-41d0-b271-3427468c5598)

I followed the documentation of the repo but can't find the mistake I'm committing. 
Any help is super appreciated, thanks

**Comment by krzko** [comment]
Hey @davide-russo-tfs,

The OpenTelemetry Github Receiver that you are using is different to the intended use cases for `run-with-telemetry`.

The one that you have enabled, was recently renamed from `git` and only provides metrics telemetry and not traces.

I donated my implementation ([27460](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27460)) of the receiver with trace telemetry capabilities to the maintainers of the OpenTelemetry Collector a couple of years ago, and it's still not been implemented.

For this reason I created a custom [OTel Collector distribution](https://github.com/krzko/otelcol-distributions/tree/main/distributions/githubactions) with the Github Actions receiver with traces enabled, so folks can take advantage of converting Github events to spans. This is the version which will work nicely with `run-with-telemetry`.

It's a shame they've taken 2 years to approve a fully implemented solution. We've been running this implementation for a couple of years without issue, so its battle hardened in the enterprise. I guess that's the nature of large Open Source projects sometimes.

**Comment by davide-russo-tfs** [comment]
Thank you very much @krzko for responding, you made it way clearer. I'll give it a try, thank you

**Comment by davide-russo-tfs** [comment]
Hi again @krzko ,
It seems like I was able to set it up and test the reception of traces. This is what I've done:

- **Configuration of the receiver**:
```
receivers:
  githubactions:
    endpoint: localhost:8085
    path: /events

exporters:
  debug:
    verbosity: basic

service:
  pipelines:
    traces:
      receivers: [githubactions]
      exporters: [debug]
```

- **Configuration of the GH workflow**:
```
name: deploy_databricks

on:
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: read-all

concurrency: 1

env: 
  DATABRICKS_TOKEN: ${{ secrets.DAB_MSD }}
  otel-exporter-otlp-endpoint: 0e07-2001-1c02-1503-aa00-7d59-180a-4e43-3d6.ngrok-free.app
  otel-service-name: deploy

jobs:
  deploy_resources:
    runs-on: self-hosted # Runs on personal laptop
    steps:
      - name: Setup telemetry
        uses: krzko/setup-telemetry@v0.5.4

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main  # Download Databricks CLI

      - name: "Deploy resources with monitoring"
        uses: krzko/run-with-telemetry@v0.5.0
        with:
          otel-exporter-otlp-endpoint: ${{ env.otel-exporter-otlp-endpoint }}
          otel-service-name: ${{ env.otel-service-name }}
          step-name: deploy_resources
          run: databricks bundle deploy

```
Since I can only test the entire thing on my laptop, I had to use _ngrok_ to obtain a public address to send the data to. Everything is redirected to `localhost:8085` (as specified in the receiver).
The URL used for the webhook during the test was: `https://0e07-2001-1c02-1503-aa00-7d59-180a-4e43-3d6.ngrok-free.app/events`.

I've noticed that most of the request end up with a "204 No content" response and nothing is printed out by the receiver, only a couple of them receive "202 Accepted" and the following lines are printed:

![Image](https://github.com/user-attachments/assets/95506a5a-bfc5-433a-997a-c12d3b2e2dc7)

There's also a request with a different path that is not accepted:

![Image](https://github.com/user-attachments/assets/05f1e44d-5ce5-4f12-9e60-255701208c1c)

What am I missing?
Thank you for your help.
